version: '3.5'
services:
  api:
    image: campifarma-ml-repository:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT:5000
      - PG_HOST=postgres
      - PG_USER=${POSTGRES_USER:-postgres}
      - PG_PASS=${POSTGRES_PASSWORD:-mudar123}
      - PG_PORT=5432
      - PG_DB=postgres
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mudar123}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
      - postgres
    volumes:
      - ./data/postgrees:/data/postgres
      - ./app/resources:/home/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - ./data/postgrees:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - default
      - postgres
    restart: unless-stopped

networks:
  default:
    name: api
  postgres:
    driver: bridge
